general:
  update-notification: true
  prefix: "&7Â» &eKudos&7: "
  debug-mode: false
  use-SQL: false
kudo-award:
  cooldown: 900
  notification:
    enabled: true
    notification-mode: "broadcast"
    enable-playsound: true
    playsound-type: "ENTITY_PLAYER_LEVELUP"
  limitation:
    enabled: true
    cooldown: 86400
    max-kudos-to-receive: 5
  rewards:
    award-item:
      enabled: true
      use-lore: false
      item: COOKIE
      item-name: "&6Hot Baked Cookie"
      item-lore:
        - "&7Ingredients:"
        - "&7- Wheat"
        - "&7- Cocoa Beans"
      amount: 1
    command-rewards:
      enabled: false
      commands:
        - xp add %kudos_player_name% 10
  milestones:
    enabled: true
    span-between-kudos: 10
    enable-playsound: true
    playsound-type: "ENTITY_FIREWORK_ROCKET_TWINKLE"
    rewards:
      award-item:
        enabled: true
        use-lore: false
        item: MILK_BUCKET
        item-name: "&6Cold milk"
        item-lore:
          - "&7Suitable for cookies"
        amount: 1
      command-rewards:
        enabled: false
        commands:
          - xp add %kudos_player_name% 10